<a href="https://colab.research.google.com/github/OgutuOndati/Dancing_Monkey/blob/main/saleprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd #useful for loading dataset
import numpy as np #to perform array

Choose dataset from local directory

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving predict_sales.csv to predict_sales.csv


LOAD DATASET INTO A SINGLE VARIABLE

In [ ]:
dataset = pd.read_csv('predict_sales.csv')
print(dataset.tail(5))

    Age   Salary  Satus
15    34   55000      0
16    54  460000      1
17    56   42000      0
18    78   30000      1
19    39   78000      0


Summerize our dataset

In [ ]:
print(dataset.shape)
print(dataset.head(6))

(20, 3)
   Age   Salary  Satus
0    18   82000      0
1    33   80000      0
2    47   25000      1
3    45   26000      1
4    46   28000      1
5    48   29000      1


Segregate our dataset into X(Input/IndependentVariable) & Y(Output/DependentVariable)

In [ ]:
X = dataset.iloc[:, :-1].values
X

array([[    18,  82000],
       [    33,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    47,  49000],
       [    50,  65000],
       [    45,  39000],
       [    46,  56000],
       [    23,  49000],
       [    34,  65000],
       [    29, 100000],
       [    36,  48000],
       [    41,  29000],
       [    34,  55000],
       [    54, 460000],
       [    56,  42000],
       [    78,  30000],
       [    39,  78000]])

In [ ]:
Y = dataset.iloc[:, -1].values
Y

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

Splitting Dataset into Train and Test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)


FEATURE SCALING
We scale our data to make all the features to contribute equally to the result
Fit_Transform- fit method is calculating the mean and variance of each of the features present in our data
Transform - Transform methos is transforming all the features using the respective mean and variance 
We want our test data to be a completely new and a surprise set for our model


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)


[[ 1.42160425 -0.33767061]
 [ 0.50334313 -0.27064714]
 [-0.61897601 -0.28022193]
 [ 0.40131412 -0.47171755]
 [ 0.50334313 -0.50044189]
 [ 0.60537214 -0.46214276]
 [-0.10883095 -0.46214276]
 [ 0.40131412 -0.20362368]
 [ 0.80943017 -0.11745065]
 [ 1.21754622  3.66458786]
 [-0.82303404 -0.11745065]
 [ 0.2992851  -0.49086711]
 [-2.45549825  0.04532063]
 [-0.82303404 -0.21319846]
 [-1.3331791   0.21766669]]


TRAINING

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

Predicting if new customer with age and salary will buy or not. 

In [ ]:
age = int(input("Enter New Customer's Age:"))
sal = int(input("Enter New Customer Salary"))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer will buy")
else:
    print("Customer will not buy")

Enter New Customer's Age:50
Enter New Customer Salary50000
[1]
Customer will buy


Prediction for all test data

In [ ]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]]


CONFUSION MATRIX

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix: ")
print(cm)


print("Accuracy of the Model: {0}%".format(accuracy_score(y_test, y_pred)*100))

Confusion Matrix: 
[[3 0]
 [0 2]]
Accuracy of the Model: 100.0%
